package main

import (
	"fmt"
	"os"
	"slices"
	"strings"
	"testing"
)

// Every quest's boss waits on its level, under the journal's name for it.
func TestQuestLevels(t *testing.T) {
	g := NewGame(1)
	for _, q := range quests {
		l := g.getLevel(q.Level)
		if l.NameKey != q.Area {
			t.Errorf("%s: %s is area.%s, the journal says area.%s", q.ID, q.Level, l.NameKey, q.Area)
		}
		switch {
		case q.Item != "" && !slices.ContainsFunc(l.Items, func(fi *FloorItem) bool { return fi.It.Name == q.Item }):
			t.Errorf("%s: no %s on %s", q.ID, q.Item, q.Level)
		case q.Item == "" && !slices.ContainsFunc(l.Monsters, func(m *Monster) bool { return m.T.ID == q.Boss }):
			t.Errorf("%s: no %s on %s", q.ID, q.Boss, q.Level)
		}
		if g.way("town", q.Level) == nil {
			t.Errorf("%s: no way from town to %s", q.ID, q.Level)
		}
	}
}

// The route walks the quest line: each boss in turn, back up and over
// to the next, then on down past the last.
func TestRouteFollowsQuestLine(t *testing.T) {
	g := NewGame(1)
	walk := func(from string) []string {
		w := []string{from}
		for id := from; len(w) < 40; {
			if id = g.routeNext(id); id == "" {
				break
			}
			w = append(w, id)
		}
		return w
	}
	want := [][]string{
		{"town", "fields", "crypt1", "crypt2", "crypt3", "crypt4"},
		{"crypt4", "crypt3", "crypt2", "crypt1", "fields", "barrow1", "barrow2"},
		{"barrow2", "barrow1", "fields", "marsh", "grotto1", "grotto2", "grotto3"},
		{"grotto3", "grotto2", "grotto1", "marsh", "fields", "town", "sanctum1"},
		{"sanctum1", "sanctum2"},
		{"sanctum2", "sanctum1", "town", "fields", "marsh", "grotto1", "grotto2", "grotto3", "abyss1", "abyss2", "abyss3"},
	}
	from := "town"
	for i := range quests {
		q := &quests[i]
		if got := walk(from); !slices.Equal(got, want[i]) {
			t.Errorf("to %s: %v, want %v", q.ID, got, want[i])
		}
		g.complete(q)
		from = q.Level
	}
	g.unseal(g.getLevel(quests[len(quests)-1].Level))
	if got := g.routeNext("abyss3"); got != "abyss4" {
		t.Errorf("past the line: %q, want abyss4", got)
	}
	if got := g.routeNext("town"); got != "fields" {
		t.Errorf("from town past the line: %q, want fields", got)
	}
}

// TestDocQuests writes docs/quests.md: the quest line as the bot walks
// it, from the quest table and the route.
//
//	make docs
func TestDocQuests(t *testing.T) {
	needShotDir(t)
	g := NewGame(42)
	L := g.L
	name := func(id string) string {
		l := g.getLevel(id)
		return fmt.Sprintf("%s (lvl %d)", areaName(L, l), l.Depth)
	}
	var b strings.Builder
	b.WriteString("# Quest line\n\n<!-- Generated by `make docs` (TestDocQuests in route_test.go) from the quest table and the route the bot walks; do not edit. -->\n\n")
	b.WriteString("```mermaid\nflowchart LR\n")
	for i, q := range quests {
		fmt.Fprintf(&b, "    %s[\"<b>%d. %s</b><br/>%s\"]\n", q.ID, i+1, L.T(q.nameKey()), name(q.Level))
		if i > 0 {
			fmt.Fprintf(&b, "    %s --> %s\n", quests[i-1].ID, q.ID)
		}
	}
	b.WriteString("```\n\n")
	b.WriteString("| # | Boss or thing | Given by | Paid by | Where | Way |\n|---|---|---|---|---|---|\n")
	from := "town"
	for i := range quests {
		q := &quests[i]
		given, paid := "", "—"
		switch {
		case q.Giver != "":
			given = L.T("monster." + q.Giver)
			paid = given
		case q.After != "":
			given = "the death of " + L.T("monster."+q.After)
		}
		var way []string
		for _, id := range g.way(from, q.Level) {
			way = append(way, name(id))
		}
		fmt.Fprintf(&b, "| %d | %s | %s | %s | %s | %s |\n", i+1, L.T(q.nameKey()), given, paid, name(q.Level), strings.Join(way, " → "))
		g.complete(q)
		from = q.Level
	}
	if err := os.WriteFile(os.Getenv("SHOTDIR")+"/quests.md", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
}
